### ISSUE TITLE
Why needs DMB on ARM?

### ISSUE THREAD

**Issue by mzer0-yu** [rigtorp/Seqlock#1]
1) I can't find any evidence shows atomic_signal_fence doesn't work on ARM.
2) Why not using atomic_thread_fence and conditional compiling instead?

Forgive my ignorance.

**Comment by rigtorp** [comment]
ARM allows reordering of stores in the store buffer. http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.den0024a/CHDCACFC.html
