### ISSUE TITLE
GCC's ordering bug seems to be fixed in trunk

### ISSUE THREAD

**Issue by naav** [rigtorp/Seqlock#2]
> We see that the compiler did indeed reorder the load of the protected data outside the critical section and the data is no longer protected from torn reads. 

This is indeed the case up until gcc 7.3 (included), but gcc trunk does not exhibit this behavior, so I assume it's been fixed. Hopefully that'll make it in 7.4.

https://godbolt.org/g/nxGRdm

**Comment by rigtorp** [comment]
Didn't see any update to my bug report:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=78778

Thanks for letting me know!

**Comment by naav** [comment]
Yeah, it's not uncommon for GCC bugs to be fixed "accidentally", as a by-product of some other unrelated change. And since there's so many tickets on the GCC bugzilla, yours may very well remain open for a long time. Perhaps consider bumping it or closing it yourself?

**Comment by rigtorp** [comment]
I added a comment on the GCC bugzilla.
